"""add markdown

Revision ID: 6bd61ae8499f
Revises: a75dc18b94b7
Create Date: 2016-10-18 21:08:51.414407

"""

# revision identifiers, used by Alembic.
revision = '6bd61ae8499f'
down_revision = 'a75dc18b94b7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
