"""fff

Revision ID: a75dc18b94b7
Revises: 2f5bfb11c903
Create Date: 2016-10-18 20:22:39.034738

"""

# revision identifiers, used by Alembic.
revision = 'a75dc18b94b7'
down_revision = '2f5bfb11c903'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
