"""use chapter 10

Revision ID: fbc133a28cb5
Revises: d66f086b258
Create Date: 2016-10-16 10:44:19.313387

"""

# revision identifiers, used by Alembic.
revision = 'fbc133a28cb5'
down_revision = 'd66f086b258'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
